%==========================================================================
%   instruction_text.m
%==========================================================================
%==========================================================================
function pages = instruction_text(which)

switch lower(which)

    case 'oneback'
        pages = {
            sprintf(['Part 1: One-Back\n\n' ...
            'You will view a stream of objects, one at a time.\n\n' ...
            'Your job is to compare each object to the one RIGHT BEFORE it (one-back).\n\n\n\n' ...
            'Same object:        press the LEFT button\n\n' ...
            'Similar object:     press the RIGHT button\n\n' ...
            'Totally different:  do not press\n\n\n\n' ...
            'Pay attention to every object, because it may reappear in later tasks.\n\n\n\n' ...
            'Press any button to start a short practice.'])
        };

    case 'oneback_pp'
        pages = {
            sprintf(['As you may have noticed in the practice:\n\n\n\n' ...
            'This object looked exactly the SAME as the one before it,\n\n' ...
            '<<IMG:same>>\n\n' ...
            'so you would press the LEFT button.\n\n\n\n' ...
            'This object looked SIMILAR, but not identical, to the one before it,\n\n' ...
            '<<IMG:similar>>\n\n' ...
            'so you would press the RIGHT button.\n\n\n\n' ...
            'Press any button to continue.'])
        };

    case 'twoback'
        pages = {
            sprintf(['Part 1: Two-Back\n\n' ...
            'After that, you will again view a stream of objects.\n\n' ...
            'This time, compare each object to the one TWO IMAGES BACK.\n\n\n\n' ...
            'Same object:        press the LEFT button\n\n' ...
            'Similar object:     press the RIGHT button\n\n' ...
            'Totally different:  do not press\n\n\n\n' ...
            'Some objects from the one-back may return here.\n\n\n\n' ...
            'Press any button to continue.'])
            sprintf(['Important note:\n\n' ...
            'The comparison moves forward one object at a time. For example:\n\n' ...
            'when image 3 appears, compare it to image 1,\n\n' ...
            'when image 4 appears, compare it to image 2,\n\n' ...
            'when image 5 appears, compare it to image 3,\n\n' ...
            'and so on.\n\n\n\n' ...
            'Press any button to start a short practice.'])
        };

    case 'twoback_pp'
        pages = {
            sprintf(['As you may have noticed in the practice:\n\n\n\n' ...
            'This object looked exactly the SAME as the one two images back,\n\n' ...
            '<<IMG:same>>\n\n' ...
            'so you would press the LEFT button.\n\n\n\n' ...
            'This object looked SIMILAR, but not identical, to the one two images back,\n\n' ...
            '<<IMG:similar>>\n\n' ...
            'so you would press the RIGHT button.\n\n\n\n' ...
            'Press any button to continue.'])
        };

    case 'final'
        pages = {
            sprintf(['You have completed the instructions and practice.\n\n' ...
            'In the actual task, you will do a one-back, then a two-back,\n\n' ...
            'repeated over four separate runs.\n\n\n\n' ...
            'Press any button to continue.'])
        };

    case 'mst'
        pages = {
            sprintf(['Part 2: Memory Test\n\n' ...
            'Finally, you will view a series of objects.\n\n' ...
            'For each one, decide whether it is old, similar, or new\n\n' ...
            'compared with the objects you saw in Part 1.\n\n\n\n' ...
            'Old:      press the LEFT button\n\n' ...
            'Similar:  press the RIGHT button\n\n' ...
            'New:      do not press\n\n\n\n' ...
            'Please let the experimenter know when you are ready.'])
        };

    otherwise
        error('instruction_text: unknown block "%s".', which);
end
end
